name: Coverage
on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: x64
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest --cov=src/ tests/
      - run: poetry run coverage xml "--include=src/*.py,tests" --fail-under=0 --ignore-errors
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
      - run: poetry run codecov
